FROM  nvidia/cudagl:10.1-base-ubuntu18.04
LABEL Author="Or Fleisher (contact@orfleisher.com)"
LABEL Title="BlendGen: Synthetic Data for Machine Learning using Blender"

# Enviorment variables
ENV PYTHONPATH "${PYTHONPATH}:/data/blendgen"
ENV PATH "$PATH:/bin/2.80/python/bin/"
ENV BLENDER_PATH "/bin/2.80"
ENV BLENDERPY "/bin/2.80/python/bin/python3.7m"
ENV BLENDERPIP "/bin/2.80/python/bin/pip3"
ENV DEBIAN_FRONTEND noninteractive
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8
ENV HW="GPU"

# Install dependencies
RUN apt-get update && apt-get install -y \
    wget \
    libopenexr-dev \
    bzip2 \
    build-essential \
    zlib1g-dev \
    libxmu-dev \
    libxi-dev \
    libxxf86vm-dev \
    libfontconfig1 \
    libxrender1

# Download and install Blender
RUN wget https://mirror.clarkson.edu/blender/release/Blender2.80/blender-2.80-linux-glibc217-x86_64.tar.bz2 \ 
    && tar -xvjf blender-2.80-linux-glibc217-x86_64.tar.bz2 --strip-components=1 -C /bin \
    && rm -rf blender-2.80-linux-glibc217-x86_64.tar.bz2 \
    && rm -rf blender-2.80-linux-glibc217-x86_64

# Download the Python source since it is not bundled with Blender
RUN wget https://www.python.org/ftp/python/3.6.8/Python-3.6.8.tgz \
    && tar -xzf Python-3.6.8.tgz \
    && cp Python-3.6.8/Include/* $BLENDER_PATH/python/include/python3.7m/ \
    && rm -rf Python-3.6.8.tgz \
    && rm -rf Python-3.6.8

# Blender comes with a super outdated version of numpy (which is needed for matplotlib / opencv) so override it with a modern one
RUN rm -rf ${BLENDER_PATH}/python/lib/python3.7/site-packages/numpy

# Copy over the python requirements file
COPY requirements.txt .

# Must first ensurepip to install Blender pip3 and install dependencies
RUN ${BLENDERPY} -m ensurepip && \
    ${BLENDERPIP} install --upgrade pip && \
    ${BLENDERPIP} install -r ./requirements.txt

# Set the working directory
WORKDIR /